export const steps = [
	{
		id: "01-02-01",
		url: "/01-02-01",
		tag: "Challenge",
		title: "A Primer on CSS Variables",
	},
	{
		id: "01-02-02",
		url: "/01-02-02",
		tag: "Solution",
		title: "Redefining CSS Variables in Different Scopes",
	},
	{
		id: "01-03-01",
		url: "/01-03-01",
		tag: "Challenge",
		title: "Create Themeable Color Shades with CSS Variables",
	},
	{
		id: "01-03-02",
		url: "/01-03-02",
		tag: "Solution",
		title: "Creating Multiple Color Spreads with CSS Variables",
	},
	{
		id: "01-04-01",
		url: "/01-04-01",
		tag: "Challenge",
		title: "Implementing Color Opacity with CSS Variables",
	},
	{
		id: "01-04-02",
		url: "/01-04-02",
		tag: "Solution",
		title: "Compose RGB Channels with alpha-value for Opacity Support",
	},
	{
		id: "01-05-01",
		url: "/01-05-01",
		tag: "Challenge",
		title: "Improve Your Developer Workflow with Tailwind CSS Plugins",
	},
	{
		id: "01-05-02",
		url: "/01-05-02",
		tag: "Solution",
		title: "Building an Example All Caps Plugin for Tailwind CSS",
	},
	{
		id: "01-06-01",
		url: "/01-06-01",
		tag: "Challenge",
		title: "Moving CSS Variable Declarations into a Tailwind CSS Plugin",
	},
	{
		id: "01-06-02",
		url: "/01-06-02",
		tag: "Solution",
		title: "Transform CSS into CSS in JS for use in a Tailwind CSS Plugin",
	},
	{
		id: "01-07-01",
		url: "/01-07-01",
		tag: "Challenge",
		title: "Convert Hex to RGB with JavaScript",
	},
	{
		id: "01-07-02",
		url: "/01-07-02",
		tag: "Solution",
		title: "Replacing Hardcoded RGB Channel Values with Function Calls",
	},
	{
		id: "01-08-01",
		url: "/01-08-01",
		tag: "Challenge",
		title: "Refactoring to Remove Hard-Coded Theme Names in Tailwind Plugin",
	},
	{
		id: "01-08-02",
		url: "/01-08-02",
		tag: "Solution",
		title: "Dynamically Adding Themes through Iteration",
	},
	{
		id: "01-09-01",
		url: "/01-09-01",
		tag: "Challenge",
		title: "Consolidating Code Concerns into a Tailwind Plugin",
	},
	{
		id: "01-09-02",
		url: "/01-09-02",
		tag: "Solution",
		title: "Configure Tailwind to Extend Themes via Plugin",
	},
	{
		id: "01-10-01",
		url: "/01-10-01",
		tag: "Challenge",
		title:
			"Testing The Multi-Theme Plugin by Replacing the Site-Wide Color in a Calendar App",
	},
	{
		id: "01-11-01",
		url: "/01-11-01",
		tag: "Challenge",
		title: "Dynamically Generate Colors From Nested Theme Objects",
	},
	{
		id: "01-11-02",
		url: "/01-11-02",
		tag: "Solution",
		title: "Create CSS Variables from Theme Objects with Recursion",
	},
	{
		id: "01-12-01",
		url: "/01-12-01",
		tag: "Challenge",
		title: "Write a Function That Replaces Hard-Coded Theme Colors",
	},
	{
		id: "01-12-02",
		url: "/01-12-02",
		tag: "Solution",
		title: "Dynamically Define Theme Colors In Your Tailwind Config",
	},
	{
		id: "01-13-01",
		url: "/01-13-01",
		tag: "Challenge",
		title: "Determine How to Pass Options to a Plugin",
	},
];
